# --------------------------------------------------------
#       ______ _             _ _____            __ _
#       |  ___(_)           | /  __ \          / _| |
#       | |_   _ _ __   __ _| | /  \/_ __ __ _| |_| |_
#       |  _| | | '_ \ / _` | | |   | '__/ _` |  _| __|
#       | |   | | | | | (_| | | \__/\ | | (_| | | | |_
#       \_|   |_|_| |_|\__,_|_|\____/_|  \__,_|_|  \__|
#
#
#
#               EverNife's Config Manager
#
#  Plugin: PixelmonEconomyBridge
#  Author: EverNife
#
# -------------------------------------------------------
Settings:
  vaultOnly_syncInterval: 10 #These checks are async, but there is no reason to use a value lower than 10 ticks