name: PixelmonEconomyBridge
version: 1.0.10
author: EverNife
main: br.com.finalcraft.pixelmoneconomybridge.PixelmonEconomyBridge
depend: [ Vault, EverNifeCore ]
softdepend:  [ FinalEconomy ]
api-version: 1.13