name: PixelmonEconomyBridge
version: 1.0.6
author: EverNife
main: br.com.finalcraft.pixelmoneconomybridge.PixelmonEconomyBridge
depend: [ Vault ]
loadbefore: [ EverNifeCore ]
softdepend:  [ FinalEconomy ]